# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='duration',
            field=models.DurationField(),
        ),
    ]
