# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldo', '0002_auto_20161203_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
