# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldo', '0003_player_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='player',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='player',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='music_type',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='timer',
            field=models.CharField(default='NA', max_length=4),
        ),
    ]
