# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waldo', '0004_auto_20161204_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
